class Constants {
  List<String> englishTitles = [
    'Sainyamulaku adhipati',
    'kannula jarina kannillu',
    'jyotirmayuda - prema svarupuda',
    'mamatanu chupina naa yesayya',
    'amma chupaledu ni prema',
    'hrudaya vanchhalu tirchuvada',
    'sadayuda na yesayya',
    'vichegali svagatamaniye',
    'adigo priyuni keka',
    'vendi bangaramulu',
    'rajuvaina na deva',
    'yesu raktame',
    'premake svagatam',
    'na nitiki adharama',
    'kavali kavali',
    'sarva saktigala deva',
    'sarvabhumiki rajaina deva',
    'na guri nive na dari nive',
    'enta chitramo....',
    'ni duḥkha dinamulu',
    'ninne talachi - ninne valachi',
    'halleluya - halleluya',
    'prabhuva hitavatsaram',
    'ni krupa bahulyame',
    'deva.... deva....',
    'ebinejara ebinejara',
    'nivu lekapote',
    'lemmu tejarillumu nivu',
    'srama dinamuna nivu krungite',
    'yesayya na deva',
    'adugamantive',
    'virigi naligina manassu',
    'venolla koniyadina',
    'stuti gitame padana',
    'deva darsinchu ma desam',
    'asrayame ni raktame',
    'prema svarupuda',
    'alochincharadela',
    'sinhasanasinudu',
    'devuni preminchuvariki',
    'prabhuva ni sannidhilo',
    'nannu balaparachuvaniyande',
    'atmiyuda ni anuragamu',
    'jagati punadulu',
    'akasamandu nivu tappa',
    'uhinchaledayya i jivitam',
    'ninne stutiyintunu',
    'gurtuchesuko manasa',
    'mahadevuda',
    'deva na devudavu nivenani',
    'sahodarulu aikyata kaligi',
    'samaptamayenu',
    'na stotra ganama',
    'gatakalamanta',
    'anukunnava',
    'ninugachuvadu narudu kadu',
    'nitone anubandham',
    'na prana dipama',
    'modati prema vidachitiva',
    'egurutunna',
    'na jyestha bhagasvami',
    'na parisuddhudavu',
    'ninnu e matramu',
    'matladumayya',
    'deva jali chupumu',
    'duramaitiva',
    'elugetti padana',
    'siramu mida',
    'andari prabhuvaina deva',
    'nammadagina devuda nanu',
    'chemmagillu kallalona kannillenta',
    'jalari o jalari',
    'yesu ni kosam',
    'vandanale ne cheyana',
    'kaluvari kondapaina',
    'padave koyila',
    'manchimanassunna',
    'egasipade anandam',
    'krupalanu talapoyuchu',
    'yesayya na yesayya',
    'yesu nive na adharamu',
    'enchitiva deva nanu',
    'intakalamu nannu kachenu',
    'yesayya ni prana tyagam',
    'divinchu maa tandri',
    'ee yogyata',
    'ni asa',
    'premante prema',
    'siluvalo nidu keka',
    'vinnapalu',
    'emivvagalanayya',
    'ananda ganalu',
    'ennatagani nannu!',
    'ni sevalonannu karigiponi!',
    'asrayamu nivenaya',
    'jiva jalama!',
    'ankitam nikankitam!',
    'paraloka mandunna ma tandri!',
    'marali marali!',
    'yesu ni anuragam!',
    'asapadaku',
    'priyuda yesayya',
    'andukonumu deva!',
    'deva na mora vinava',
    'kalam marina',
    'anandamananda',
    'unnatamandunna deva!',
    'yesayya ni premaku',
    'aradhana',
    'akasama',
    'chuche kannuliyuma',
    'na priyudu',
    'golgata',
    'na balama'
  ];

  List<String> teluguTitles = [
    'సైన్యములకు అధిపతి',
    'కన్నుల జారిన కన్నీళ్ళు',
    'జ్యోతిర్మయుడా - ప్రేమ స్వరూపుడా',
    'మమతను చూపిన నా యేసయ్యా',
    'అమ్మ చూపలేదు నీ ప్రేమ ',
    'హృదయ వాంఛలు తీర్చువాడా ',
    'సదయుడా నా యేసయ్య',
    'వీచేగాలి స్వాగతమనియే',
    'అదిగో ప్రియుని కేక',
    'వెండి బంగారములు',
    'రాజువైన నా దేవా ',
    'యేసు రక్తమే',
    'ప్రేమకే స్వాగతం',
    'నా నీతికి ఆధారమా',
    'కావాలి కావాలి',
    'సర్వ శక్తిగల దేవా',
    'సర్వభూమికి రాజైన దేవా',
    'నా గురి నీవే నా దరి నీవే',
    'ఎంత చిత్రమో.... ',
    'నీ దుఃఖ దినములు',
    'నిన్నే తలచి - నిన్నే వలచి',
    ' హల్లెలూయా - హల్లెలూయా',
    ' ప్రభువా హితవత్సరం',
    'నీ కృప బాహుళ్యమే',
    ' దేవా.... దేవా....',
    ' ఎబినేజర ఎబినేజర ',
    ' నీవు లేకపోతే',
    'లెమ్ము తేజరిల్లుము నీవు',
    'శ్రమ దినమున నీవు కృంగితే',
    'యేసయ్యా నా దేవా',
    ' అడుగమంటివే',
    'విరిగి నలిగిన మనస్సు',
    ' వేనోళ్ళ కొనియాడిన',
    'స్తుతి గీతమే పాడనా ',
    ' దేవా దర్శించు మా దేశం',
    ' ఆశ్రయమే నీ రక్తమే',
    'ప్రేమా స్వరూపుడా',
    ' ఆలోచించరదేలా',
    'సింహాసనాసీనుడు',
    ' దేవుని ప్రేమించువారికి',
    'ప్రభువా నీ సన్నిధిలో',
    'నన్ను బలపరచువానియందే',
    'ఆత్మీయుడా నీ అనురాగము',
    ' జగతి పునాదులు',
    ' ఆకాశమందు నీవు తప్ప',
    'ఊహించలేదయ్యా ఈ జీవితం',
    ' నిన్నే స్తుతియింతును',
    'గుర్తుచేసుకో మనసా',
    ' మహాదేవుడా',
    'దేవా నా దేవుడవు నీవేనని',
    'సహోదరులు ఐక్యత కలిగి',
    'సమాప్తమాయెను',
    ' నా స్తోత్ర గానమా',
    ' గతకాలమంత',
    'అనుకున్నావా',
    'నినుగాచువాడు నరుడు కాడు',
    'నీతోనే అనుబంధం',
    'నా ప్రాణ దీపమా',
    'మొదటి ప్రేమ విడచితివా',
    'ఎగురుతున్న',
    'నా జ్యేష్ఠ భాగస్వామి',
    'నా పరిశుద్ధుడవు',
    'నిన్ను ఏ మాత్రము',
    'మాట్లాడుమయ్య',
    'దేవా జాలి చూపుము',
    'దూరమైతివా',
    'ఎలుగెత్తి పాడనా',
    'శిరము మీద',
    'అందరి ప్రభువైన దేవా',
    'నమ్మదగిన దేవుడా నను',
    'చెమ్మగిల్లు కళ్ళలోన కన్నీళ్ళెంత',
    'జాలరీ ఓ జాలరీ',
    'యేసు నీ కోసం',
    'వందనాలే నే చేయనా',
    'కలువరి కొండపైనా',
    'పాడవే కోయిలా',
    'మంచిమనస్సున్న',
    'ఎగసిపడే ఆనందం',
    'కృపలను తలపోయుచు',
    'యేసయ్యా నా యేసయ్యా ',
    'యేసూ నీవే నా ఆధారము',
    'ఎంచితివా దేవా నను',
    'ఇంతకాలము నన్ను కాచెను',
    'యేసయ్యా నీ ప్రాణ త్యాగం',
    'దీవించు మా తండ్రి',
    'ఏ యోగ్యత',
    'నీ ఆశ',
    'ప్రేమంటే ప్రేమ',
    'సిలువలో నీదు కేక',
    'విన్నపాలు',
    'ఏమివ్వగలనయ్య',
    'ఆనంద గానాలు',
    'ఎన్నతగని నన్ను!',
    'నీ సేవలోనన్ను కరిగిపోని!',
    'ఆశ్రయము నీవేనయా',
    'జీవ జలమా!',
    'అంకితం నీకంకితం!',
    'పరలోక మందున్న మా తండ్రి!',
    'మారాలి మారాలి!',
    'యేసూ నీ అనురాగం!',
    'ఆశపడకు',
    'ప్రియుడా యేసయ్యా',
    'అందుకొనుము దేవా!',
    'దేవా నా మొర వినవా',
    'కాలం మారినా',
    'ఆనందమానంద',
    'ఉన్నతమందున్న దేవా!',
    'యేసయ్యా నీ ప్రేమకు',
    'ఆరాధనా',
    'ఆకాశమా',
    'చూచే కన్నులీయుమా',
    'నా ప్రియుడు',
    'గోల్గతా',
    ' నా బలమా '
  ];

  Map<String, String> teluguNEnglish = {
    'సైన్యములకు అధిపతి': 'Sainyamulaku adhipati',
    'కన్నుల జారిన కన్నీళ్ళు': 'kannula jarina kannillu',
    'జ్యోతిర్మయుడా - ప్రేమ స్వరూపుడా': 'jyotirmayuda - prema svarupuda',
    'మమతను చూపిన నా యేసయ్యా': 'mamatanu chupina naa yesayya',
    'అమ్మ చూపలేదు నీ ప్రేమ ': 'amma chupaledu ni prema',
    'హృదయ వాంఛలు తీర్చువాడా ': 'hrudaya vanchhalu tirchuvada',
    'సదయుడా నా యేసయ్య': 'sadayuda na yesayya',
    'వీచేగాలి స్వాగతమనియే': 'vichegali svagatamaniye',
    'అదిగో ప్రియుని కేక': 'adigo priyuni keka',
    'వెండి బంగారములు': 'vendi bangaramulu',
    'రాజువైన నా దేవా ': 'rajuvaina na deva',
    'యేసు రక్తమే': 'yesu raktame',
    'ప్రేమకే స్వాగతం': 'premake svagatam',
    'నా నీతికి ఆధారమా': 'na nitiki adharama',
    'కావాలి కావాలి': 'kavali kavali',
    'సర్వ శక్తిగల దేవా': 'sarva saktigala deva',
    'సర్వభూమికి రాజైన దేవా': 'sarvabhumiki rajaina deva',
    'నా గురి నీవే నా దరి నీవే': 'na guri nive na dari nive',
    'ఎంత చిత్రమో.... ': 'enta chitramo....',
    'నీ దుఃఖ దినములు': 'ni duḥkha dinamulu',
    'నిన్నే తలచి - నిన్నే వలచి': 'ninne talachi - ninne valachi',
    ' హల్లెలూయా - హల్లెలూయా': 'halleluya - halleluya',
    ' ప్రభువా హితవత్సరం': 'prabhuva hitavatsaram',
    'నీ కృప బాహుళ్యమే': 'ni krupa bahulyame',
    ' దేవా.... దేవా....': 'deva.... deva....',
    ' ఎబినేజర ఎబినేజర ': 'ebinejara ebinejara',
    ' నీవు లేకపోతే': 'nivu lekapote',
    'లెమ్ము తేజరిల్లుము నీవు': 'lemmu tejarillumu nivu',
    'శ్రమ దినమున నీవు కృంగితే': 'srama dinamuna nivu krungite',
    'యేసయ్యా నా దేవా': 'yesayya na deva',
    ' అడుగమంటివే': 'adugamantive',
    'విరిగి నలిగిన మనస్సు': 'virigi naligina manassu',
    ' వేనోళ్ళ కొనియాడిన': 'venolla koniyadina',
    'స్తుతి గీతమే పాడనా ': 'stuti gitame padana',
    ' దేవా దర్శించు మా దేశం': 'deva darsinchu ma desam',
    ' ఆశ్రయమే నీ రక్తమే': 'asrayame ni raktame',
    'ప్రేమా స్వరూపుడా': 'prema svarupuda',
    ' ఆలోచించరదేలా': 'alochincharadela',
    'సింహాసనాసీనుడు': 'sinhasanasinudu',
    ' దేవుని ప్రేమించువారికి': 'devuni preminchuvariki',
    'ప్రభువా నీ సన్నిధిలో': 'prabhuva ni sannidhilo',
    'నన్ను బలపరచువానియందే': 'nannu balaparachuvaniyande',
    'ఆత్మీయుడా నీ అనురాగము': 'atmiyuda ni anuragamu',
    ' జగతి పునాదులు': 'jagati punadulu',
    ' ఆకాశమందు నీవు తప్ప': 'akasamandu nivu tappa',
    'ఊహించలేదయ్యా ఈ జీవితం': 'uhinchaledayya i jivitam',
    ' నిన్నే స్తుతియింతును': 'ninne stutiyintunu',
    'గుర్తుచేసుకో మనసా': 'gurtuchesuko manasa',
    ' మహాదేవుడా': 'mahadevuda',
    'దేవా నా దేవుడవు నీవేనని': 'deva na devudavu nivenani',
    'సహోదరులు ఐక్యత కలిగి': 'sahodarulu aikyata kaligi',
    'సమాప్తమాయెను': 'samaptamayenu',
    ' నా స్తోత్ర గానమా': 'na stotra ganama',
    ' గతకాలమంత': 'gatakalamanta',
    'అనుకున్నావా': 'anukunnava',
    'నినుగాచువాడు నరుడు కాడు': 'ninugachuvadu narudu kadu',
    'నీతోనే అనుబంధం': 'nitone anubandham',
    'నా ప్రాణ దీపమా': 'na prana dipama',
    'మొదటి ప్రేమ విడచితివా': 'modati prema vidachitiva',
    'ఎగురుతున్న': 'egurutunna',
    'నా జ్యేష్ఠ భాగస్వామి': 'na jyestha bhagasvami',
    'నా పరిశుద్ధుడవు': 'na parisuddhudavu',
    'నిన్ను ఏ మాత్రము': 'ninnu e matramu',
    'మాట్లాడుమయ్య': 'matladumayya',
    'దేవా జాలి చూపుము': 'deva jali chupumu',
    'దూరమైతివా': 'duramaitiva',
    'ఎలుగెత్తి పాడనా': 'elugetti padana',
    'శిరము మీద': 'siramu mida',
    'అందరి ప్రభువైన దేవా': 'andari prabhuvaina deva',
    'నమ్మదగిన దేవుడా నను': 'nammadagina devuda nanu',
    'చెమ్మగిల్లు కళ్ళలోన కన్నీళ్ళెంత': 'chemmagillu kallalona kannillenta',
    'జాలరీ ఓ జాలరీ': 'jalari o jalari',
    'యేసు నీ కోసం': 'yesu ni kosam',
    'వందనాలే నే చేయనా': 'vandanale ne cheyana',
    'కలువరి కొండపైనా': 'kaluvari kondapaina',
    'పాడవే కోయిలా': 'padave koyila',
    'మంచిమనస్సున్న': 'manchimanassunna',
    'ఎగసిపడే ఆనందం': 'egasipade anandam',
    'కృపలను తలపోయుచు': 'krupalanu talapoyuchu',
    'యేసయ్యా నా యేసయ్యా ': 'yesayya na yesayya',
    'యేసూ నీవే నా ఆధారము': 'yesu nive na adharamu',
    'ఎంచితివా దేవా నను': 'enchitiva deva nanu',
    'ఇంతకాలము నన్ను కాచెను': 'intakalamu nannu kachenu',
    'యేసయ్యా నీ ప్రాణ త్యాగం': 'yesayya ni prana tyagam',
    'దీవించు మా తండ్రి': 'divinchu maa tandri',
    'ఏ యోగ్యత': 'ee yogyata',
    'నీ ఆశ': 'ni asa',
    'ప్రేమంటే ప్రేమ': 'premante prema',
    'సిలువలో నీదు కేక': 'siluvalo nidu keka',
    'విన్నపాలు': 'vinnapalu',
    'ఏమివ్వగలనయ్య': 'emivvagalanayya',
    'ఆనంద గానాలు': 'ananda ganalu',
    'ఎన్నతగని నన్ను!': 'ennatagani nannu!',
    'నీ సేవలోనన్ను కరిగిపోని!': 'ni sevalonannu karigiponi!',
    'ఆశ్రయము నీవేనయా': 'asrayamu nivenaya',
    'జీవ జలమా!': 'jiva jalama!',
    'అంకితం నీకంకితం!': 'ankitam nikankitam!',
    'పరలోక మందున్న మా తండ్రి!': 'paraloka mandunna ma tandri!',
    'మారాలి మారాలి!': 'marali marali!',
    'యేసూ నీ అనురాగం!': 'yesu ni anuragam!',
    'ఆశపడకు': 'asapadaku',
    'ప్రియుడా యేసయ్యా': 'priyuda yesayya',
    'అందుకొనుము దేవా!': 'andukonumu deva!',
    'దేవా నా మొర వినవా': 'deva na mora vinava',
    'కాలం మారినా': 'kalam marina',
    'ఆనందమానంద': 'anandamananda',
    'ఉన్నతమందున్న దేవా!': 'unnatamandunna deva!',
    'యేసయ్యా నీ ప్రేమకు': 'yesayya ni premaku',
    'ఆరాధనా': 'aradhana',
    'ఆకాశమా': 'akasama',
    'చూచే కన్నులీయుమా': 'chuche kannuliyuma',
    'నా ప్రియుడు': 'na priyudu',
    'గోల్గతా': 'golgata',
    ' నా బలమా ': 'na balama'
  };
}

String getLanguageTitle(String code) {
  return code == 'te' ? 'TEL' : 'EN';
}
